-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.campaign_assets (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  campaign_id uuid NOT NULL,
  asset_type text NOT NULL CHECK (asset_type = ANY (ARRAY['welcome_message'::text, 'home_screen_image'::text, 'splash_screen_image'::text, 'print_slip_template'::text, 'whatsapp_campaign_image'::text])),
  title text,
  content text,
  file_url text,
  file_mime_type text,
  platform text NOT NULL DEFAULT 'all'::text CHECK (platform = ANY (ARRAY['all'::text, 'mobile'::text, 'web'::text])),
  is_active boolean NOT NULL DEFAULT true,
  display_order integer NOT NULL DEFAULT 1,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_by_user_id uuid,
  updated_by_user_id uuid,
  CONSTRAINT campaign_assets_pkey PRIMARY KEY (id),
  CONSTRAINT campaign_assets_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id),
  CONSTRAINT campaign_assets_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(id),
  CONSTRAINT campaign_assets_updated_by_user_id_fkey FOREIGN KEY (updated_by_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.campaigns (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  description text,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'active'::text, 'closed'::text])),
  default_language text NOT NULL DEFAULT 'en'::text,
  supported_languages ARRAY NOT NULL DEFAULT ARRAY['en'::text],
  created_by uuid,
  updated_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  is_deleted boolean NOT NULL DEFAULT false,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_by_user_id uuid,
  updated_by_user_id uuid,
  is_hierarchy_locked boolean NOT NULL DEFAULT false,
  CONSTRAINT campaigns_pkey PRIMARY KEY (id),
  CONSTRAINT campaigns_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(id),
  CONSTRAINT campaigns_updated_by_user_id_fkey FOREIGN KEY (updated_by_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.castes (
  id integer NOT NULL DEFAULT nextval('castes_id_seq'::regclass),
  name text NOT NULL UNIQUE,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT castes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.educations (
  id integer NOT NULL DEFAULT nextval('educations_id_seq'::regclass),
  name text NOT NULL UNIQUE,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT educations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.geo_units (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  campaign_id uuid NOT NULL,
  parent_id uuid,
  name text NOT NULL,
  level integer NOT NULL CHECK (level >= 1),
  is_booth boolean NOT NULL DEFAULT false,
  display_order integer NOT NULL DEFAULT 1,
  is_active boolean NOT NULL DEFAULT true,
  is_deleted boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_by_user_id uuid,
  updated_by_user_id uuid,
  path text,
  booth_number text,
  ancestors ARRAY DEFAULT '{}'::uuid[],
  CONSTRAINT geo_units_pkey PRIMARY KEY (id),
  CONSTRAINT geo_units_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id),
  CONSTRAINT geo_units_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.geo_units(id),
  CONSTRAINT geo_units_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(id),
  CONSTRAINT geo_units_updated_by_user_id_fkey FOREIGN KEY (updated_by_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.occupations (
  id integer NOT NULL DEFAULT nextval('occupations_id_seq'::regclass),
  name text NOT NULL UNIQUE,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT occupations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.passcodes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  campaign_id uuid NOT NULL,
  geo_unit_id uuid NOT NULL,
  role text NOT NULL CHECK (role = ANY (ARRAY['admin'::text, 'volunteer'::text])),
  passcode text NOT NULL UNIQUE,
  is_active boolean NOT NULL DEFAULT true,
  expires_at timestamp with time zone,
  last_used_at timestamp with time zone,
  last_used_by uuid,
  batch_id uuid,
  generated_by uuid,
  generated_at timestamp with time zone NOT NULL DEFAULT now(),
  is_deleted boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_by_user_id uuid,
  updated_by_user_id uuid,
  CONSTRAINT passcodes_pkey PRIMARY KEY (id),
  CONSTRAINT passcodes_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id),
  CONSTRAINT passcodes_geo_unit_id_fkey FOREIGN KEY (geo_unit_id) REFERENCES public.geo_units(id),
  CONSTRAINT passcodes_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(id),
  CONSTRAINT passcodes_updated_by_user_id_fkey FOREIGN KEY (updated_by_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.religions (
  id integer NOT NULL DEFAULT nextval('religions_id_seq'::regclass),
  name text NOT NULL UNIQUE,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT religions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.sub_castes (
  id integer NOT NULL DEFAULT nextval('sub_castes_id_seq'::regclass),
  caste_id integer,
  name text NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT sub_castes_pkey PRIMARY KEY (id),
  CONSTRAINT sub_castes_caste_id_fkey FOREIGN KEY (caste_id) REFERENCES public.castes(id)
);
CREATE TABLE public.survey_options (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  survey_question_id uuid NOT NULL,
  code text NOT NULL,
  option_text text NOT NULL,
  is_other boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  display_order integer NOT NULL DEFAULT 1,
  is_deleted boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_by_user_id uuid,
  updated_by_user_id uuid,
  campaign_id uuid,
  CONSTRAINT survey_options_pkey PRIMARY KEY (id),
  CONSTRAINT survey_options_survey_question_id_fkey FOREIGN KEY (survey_question_id) REFERENCES public.survey_questions(id),
  CONSTRAINT survey_options_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(id),
  CONSTRAINT survey_options_updated_by_user_id_fkey FOREIGN KEY (updated_by_user_id) REFERENCES public.users(id),
  CONSTRAINT survey_options_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id)
);
CREATE TABLE public.survey_questions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  survey_id uuid NOT NULL,
  code text NOT NULL,
  question_text text NOT NULL,
  allow_multiple boolean NOT NULL DEFAULT false,
  allow_other boolean NOT NULL DEFAULT false,
  display_order integer NOT NULL DEFAULT 1,
  is_mandatory boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  is_deleted boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_by_user_id uuid,
  updated_by_user_id uuid,
  campaign_id uuid,
  CONSTRAINT survey_questions_pkey PRIMARY KEY (id),
  CONSTRAINT survey_questions_survey_id_fkey FOREIGN KEY (survey_id) REFERENCES public.surveys(id),
  CONSTRAINT survey_questions_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(id),
  CONSTRAINT survey_questions_updated_by_user_id_fkey FOREIGN KEY (updated_by_user_id) REFERENCES public.users(id),
  CONSTRAINT survey_questions_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id)
);
CREATE TABLE public.survey_response_options (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  survey_response_id uuid NOT NULL,
  survey_question_id uuid NOT NULL,
  survey_option_id uuid NOT NULL,
  other_text text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT survey_response_options_pkey PRIMARY KEY (id),
  CONSTRAINT survey_response_options_survey_response_id_fkey FOREIGN KEY (survey_response_id) REFERENCES public.survey_responses(id),
  CONSTRAINT survey_response_options_survey_question_id_fkey FOREIGN KEY (survey_question_id) REFERENCES public.survey_questions(id),
  CONSTRAINT survey_response_options_survey_option_id_fkey FOREIGN KEY (survey_option_id) REFERENCES public.survey_options(id)
);
CREATE TABLE public.survey_responses (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  campaign_id uuid NOT NULL,
  survey_id uuid NOT NULL,
  voter_id uuid NOT NULL,
  geo_unit_id uuid NOT NULL,
  collected_by_passcode_id uuid,
  status text NOT NULL DEFAULT 'completed'::text CHECK (status = ANY (ARRAY['draft'::text, 'completed'::text])),
  latitude numeric,
  longitude numeric,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  client_response_id text,
  synced_at timestamp with time zone,
  is_deleted boolean NOT NULL DEFAULT false,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_by_user_id uuid,
  updated_by_user_id uuid,
  created_via_passcode_id uuid,
  CONSTRAINT survey_responses_pkey PRIMARY KEY (id),
  CONSTRAINT survey_responses_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id),
  CONSTRAINT survey_responses_survey_id_fkey FOREIGN KEY (survey_id) REFERENCES public.surveys(id),
  CONSTRAINT survey_responses_voter_id_fkey FOREIGN KEY (voter_id) REFERENCES public.voters(id),
  CONSTRAINT survey_responses_geo_unit_id_fkey FOREIGN KEY (geo_unit_id) REFERENCES public.geo_units(id),
  CONSTRAINT survey_responses_collected_by_passcode_id_fkey FOREIGN KEY (collected_by_passcode_id) REFERENCES public.passcodes(id),
  CONSTRAINT survey_responses_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(id),
  CONSTRAINT survey_responses_updated_by_user_id_fkey FOREIGN KEY (updated_by_user_id) REFERENCES public.users(id),
  CONSTRAINT survey_responses_created_via_passcode_id_fkey FOREIGN KEY (created_via_passcode_id) REFERENCES public.passcodes(id)
);
CREATE TABLE public.surveys (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  campaign_id uuid NOT NULL,
  code text NOT NULL,
  title text NOT NULL,
  description text,
  is_mandatory boolean NOT NULL DEFAULT false,
  allow_multiple_submissions boolean NOT NULL DEFAULT false,
  display_order integer NOT NULL DEFAULT 1,
  is_deleted boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_by_user_id uuid,
  updated_by_user_id uuid,
  is_active boolean NOT NULL DEFAULT true,
  CONSTRAINT surveys_pkey PRIMARY KEY (id),
  CONSTRAINT surveys_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id),
  CONSTRAINT surveys_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(id),
  CONSTRAINT surveys_updated_by_user_id_fkey FOREIGN KEY (updated_by_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.user_passcode_sessions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  passcode_id uuid NOT NULL,
  campaign_id uuid NOT NULL,
  first_used_at timestamp with time zone NOT NULL DEFAULT now(),
  last_used_at timestamp with time zone,
  is_active boolean NOT NULL DEFAULT true,
  CONSTRAINT user_passcode_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT user_passcode_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT user_passcode_sessions_passcode_id_fkey FOREIGN KEY (passcode_id) REFERENCES public.passcodes(id),
  CONSTRAINT user_passcode_sessions_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  phone text NOT NULL UNIQUE,
  name text NOT NULL,
  email text,
  device_id text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT users_pkey PRIMARY KEY (id)
);
CREATE TABLE public.voters (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  campaign_id uuid NOT NULL,
  geo_unit_id uuid NOT NULL,
  epic_id text,
  vid text,
  vid_2 text,
  section_number text,
  section_name text,
  part_no text,
  name text NOT NULL,
  age integer CHECK (age IS NULL OR age >= 0 AND age <= 150),
  gender text CHECK (gender = ANY (ARRAY['M'::text, 'F'::text, 'O'::text])),
  birth_date date,
  phone text,
  email text,
  house_no text,
  address text,
  religion_id integer,
  caste_id integer,
  sub_caste_id integer,
  education_id integer,
  occupation_id integer,
  relation_name text,
  relation text,
  is_dead boolean NOT NULL DEFAULT false,
  is_rented boolean NOT NULL DEFAULT false,
  is_shifted boolean NOT NULL DEFAULT false,
  favorability text CHECK (favorability = ANY (ARRAY['support'::text, 'neutral'::text, 'oppose'::text])),
  last_visited_at timestamp with time zone,
  last_visited_by uuid,
  is_deleted boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_by_user_id uuid,
  updated_by_user_id uuid,
  geo_unit_path text,
  ancestors ARRAY DEFAULT '{}'::uuid[],
  CONSTRAINT voters_pkey PRIMARY KEY (id),
  CONSTRAINT voters_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id),
  CONSTRAINT voters_geo_unit_id_fkey FOREIGN KEY (geo_unit_id) REFERENCES public.geo_units(id),
  CONSTRAINT voters_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(id),
  CONSTRAINT voters_updated_by_user_id_fkey FOREIGN KEY (updated_by_user_id) REFERENCES public.users(id),
  CONSTRAINT voters_religion_id_fkey FOREIGN KEY (religion_id) REFERENCES public.religions(id),
  CONSTRAINT voters_caste_id_fkey FOREIGN KEY (caste_id) REFERENCES public.castes(id),
  CONSTRAINT voters_sub_caste_id_fkey FOREIGN KEY (sub_caste_id) REFERENCES public.sub_castes(id),
  CONSTRAINT voters_education_id_fkey FOREIGN KEY (education_id) REFERENCES public.educations(id),
  CONSTRAINT voters_occupation_id_fkey FOREIGN KEY (occupation_id) REFERENCES public.occupations(id)
);