// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'voter.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$VoterImpl _$$VoterImplFromJson(Map<String, dynamic> json) => _$VoterImpl(
  id: json['id'] as String,
  campaignId: json['campaign_id'] as String?,
  geoUnitId: json['geo_unit_id'] as String?,
  epicId: json['epic_id'] as String?,
  vid: json['vid'] as String?,
  vid2: json['vid_2'] as String?,
  sectionNumber: json['section_number'] as String?,
  sectionName: json['section_name'] as String?,
  partNo: json['part_no'] as String?,
  name: json['name'] as String?,
  nameLocal: json['name_local'] as String?,
  age: (json['age'] as num?)?.toInt(),
  gender: _genderFromJson(json['gender']),
  birthDate: json['birth_date'] as String?,
  phone: json['phone'] as String?,
  email: json['email'] as String?,
  houseNo: json['house_no'] as String?,
  address: json['address'] as String?,
  addressLocal: json['address_local'] as String?,
  sectionNameLocal: json['section_name_local'] as String?,
  relationNameLocal: json['relation_name_local'] as String?,
  religionId: (json['religion_id'] as num?)?.toInt(),
  casteId: (json['caste_id'] as num?)?.toInt(),
  subCasteId: (json['sub_caste_id'] as num?)?.toInt(),
  educationId: (json['education_id'] as num?)?.toInt(),
  occupationId: (json['occupation_id'] as num?)?.toInt(),
  relationName: json['relation_name'] as String?,
  relation: json['relation'] as String?,
  isDead: json['is_dead'] == null ? false : _boolFromInt(json['is_dead']),
  isRented: json['is_rented'] == null ? false : _boolFromInt(json['is_rented']),
  isShifted: json['is_shifted'] == null
      ? false
      : _boolFromInt(json['is_shifted']),
  shiftedHouseNo: json['shifted_house_no'] as String?,
  shiftedAddress: json['shifted_address'] as String?,
  favorability: json['favorability'] == null
      ? VoterFavorability.neutral
      : _favorabilityFromJson(json['favorability']),
  lastVisitedAt: json['last_visited_at'] as String?,
  lastVisitedBy: json['last_visited_by'] as String?,
  isDeleted: json['is_deleted'] == null
      ? false
      : _boolFromInt(json['is_deleted']),
  createdAt: json['created_at'] as String?,
  updatedAt: json['updated_at'] as String?,
  metadata: json['metadata'] as String?,
  createdByUserId: json['created_by_user_id'] as String?,
  updatedByUserId: json['updated_by_user_id'] as String?,
  geoUnitPath: json['geo_unit_path'] as String?,
  ancestors: json['ancestors'] as String?,
  latitude: _doubleFromDynamic(json['latitude']),
  longitude: _doubleFromDynamic(json['longitude']),
  geoAddress: json['geo_address'] as String?,
  isPolled: json['is_polled'] == null ? false : _boolFromInt(json['is_polled']),
  serialNumber: (json['serial_number'] as num?)?.toInt(),
  polledAt: json['polled_at'] as String?,
  polledByUserId: json['polled_by_user_id'] as String?,
);

Map<String, dynamic> _$$VoterImplToJson(_$VoterImpl instance) =>
    <String, dynamic>{
      'id': instance.id,
      'campaign_id': instance.campaignId,
      'geo_unit_id': instance.geoUnitId,
      'epic_id': instance.epicId,
      'vid': instance.vid,
      'vid_2': instance.vid2,
      'section_number': instance.sectionNumber,
      'section_name': instance.sectionName,
      'part_no': instance.partNo,
      'name': instance.name,
      'name_local': instance.nameLocal,
      'age': instance.age,
      'gender': _genderToJson(instance.gender),
      'birth_date': instance.birthDate,
      'phone': instance.phone,
      'email': instance.email,
      'house_no': instance.houseNo,
      'address': instance.address,
      'address_local': instance.addressLocal,
      'section_name_local': instance.sectionNameLocal,
      'relation_name_local': instance.relationNameLocal,
      'religion_id': instance.religionId,
      'caste_id': instance.casteId,
      'sub_caste_id': instance.subCasteId,
      'education_id': instance.educationId,
      'occupation_id': instance.occupationId,
      'relation_name': instance.relationName,
      'relation': instance.relation,
      'is_dead': _boolToInt(instance.isDead),
      'is_rented': _boolToInt(instance.isRented),
      'is_shifted': _boolToInt(instance.isShifted),
      'shifted_house_no': instance.shiftedHouseNo,
      'shifted_address': instance.shiftedAddress,
      'favorability': _favorabilityToJson(instance.favorability),
      'last_visited_at': instance.lastVisitedAt,
      'last_visited_by': instance.lastVisitedBy,
      'is_deleted': _boolToInt(instance.isDeleted),
      'created_at': instance.createdAt,
      'updated_at': instance.updatedAt,
      'metadata': instance.metadata,
      'created_by_user_id': instance.createdByUserId,
      'updated_by_user_id': instance.updatedByUserId,
      'geo_unit_path': instance.geoUnitPath,
      'ancestors': instance.ancestors,
      'latitude': _doubleToString(instance.latitude),
      'longitude': _doubleToString(instance.longitude),
      'geo_address': instance.geoAddress,
      'is_polled': _boolToInt(instance.isPolled),
      'serial_number': instance.serialNumber,
      'polled_at': instance.polledAt,
      'polled_by_user_id': instance.polledByUserId,
    };
